// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKF3XsAmBfrBqkZCLr1FahniFPbMvMJPM',
    appId: '1:329281196829:android:9bfd9e6624ae817c6007f4',
    messagingSenderId: '329281196829',
    projectId: 'caresyncm',
    storageBucket: 'caresyncm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLh2CRS-iL9E2P5uchgqVGQqMfqEX7SeI',
    appId: '1:329281196829:ios:71b46c4fe97553336007f4',
    messagingSenderId: '329281196829',
    projectId: 'caresyncm',
    storageBucket: 'caresyncm.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLh2CRS-iL9E2P5uchgqVGQqMfqEX7SeI',
    appId: '1:329281196829:ios:71b46c4fe97553336007f4',
    messagingSenderId: '329281196829',
    projectId: 'caresyncm',
    storageBucket: 'caresyncm.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzeYOJS6A0uZFl-x8kplK8e4IvUYGqrcM',
    appId: '1:329281196829:web:72bc6ea6b4c3531a6007f4',
    messagingSenderId: '329281196829',
    projectId: 'caresyncm',
    authDomain: 'caresyncm.firebaseapp.com',
    storageBucket: 'caresyncm.firebasestorage.app',
    measurementId: 'G-TSDFKZ46S3',
  );

  // Web configuration (use the same values as the web/windows entry above).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzeYOJS6A0uZFl-x8kplK8e4IvUYGqrcM',
    appId: '1:329281196829:web:72bc6ea6b4c3531a6007f4',
    messagingSenderId: '329281196829',
    projectId: 'caresyncm',
    authDomain: 'caresyncm.firebaseapp.com',
    storageBucket: 'caresyncm.firebasestorage.app',
    measurementId: 'G-TSDFKZ46S3',
  );
}
