import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'firebase_options.dart';

import 'auth/home_page.dart';
import 'auth/login_page.dart';
import 'auth/signup_page.dart';
import 'auth/email_verification_page.dart';
import 'auth/otp_verification_page.dart';
import 'dashboard/dashboard_page.dart';
import 'features/directory/browse_and_book.dart';
import 'features/directory/admin_page.dart';
import 'features/admin/admin_dashboard.dart';
import 'features/admin/medical_info_admin.dart';
import 'features/admin/medications_admin.dart';
import 'features/admin/health_guides_admin.dart';
import 'package:caresync/features/medical_records/medical_records_page.dart';
import 'package:caresync/features/appointments/appointment_page.dart';
import 'package:caresync/features/alarms/alarm_settings_page.dart';
import 'package:caresync/shared/services/notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options generated by FlutterFire.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize Hive for local storage used by medications/appointments
  await Hive.initFlutter();

  // Initialize notification service for medication and appointment alarms
  await NotificationService().initialize();

  runApp(const CareSyncApp());
}

class CareSyncApp extends StatelessWidget {
  const CareSyncApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CareSync',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      initialRoute: '/',
      routes: {
        '/': (_) => const HomePage(),
        '/login': (_) => const LoginPage(),
        '/signup': (_) => const SignupPage(),
        '/verify-email': (_) => const EmailVerificationPage(),
        '/dashboard': (_) => const DashboardPage(),
        '/directory/browse': (_) => const BrowseAndBookPage(),
        '/directory/admin': (_) => const DirectoryAdminPage(),
        '/medical-records': (_) => const MedicalRecordsPage(),
        '/appointments': (_) => const AppointmentsPage(),
        '/alarm-settings': (_) => const AlarmSettingsPage(),
        '/admin': (_) => const AdminDashboard(),
        '/admin/medical-info': (_) => const MedicalInfoAdminPage(),
        '/admin/medications': (_) => const MedicationsAdminPage(),
        '/admin/health-guides': (_) => const HealthGuidesAdminPage(),
      },
      onGenerateRoute: (settings) {
        if (settings.name == '/otp-verification') {
          final args = settings.arguments as Map<String, dynamic>;
          return MaterialPageRoute(
            builder: (context) => OTPVerificationPage(
              email: args['email'] as String,
              isSignup: args['isSignup'] as bool? ?? false,
            ),
          );
        }
        return null;
      },
    );
  }
}
