// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAveqno_Ei17FEExgH-w6VVuxXHYi2opyw',
    appId: '1:623777701983:web:1ce03320ffe256fbf37bea',
    messagingSenderId: '623777701983',
    projectId: 'caresync-app-955fa',
    authDomain: 'caresync-app-955fa.firebaseapp.com',
    storageBucket: 'caresync-app-955fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5x9rBsrcZmPEvQWrj7zEKjd2D9W2XSY',
    appId: '1:623777701983:android:786f4ef929288067f37bea',
    messagingSenderId: '623777701983',
    projectId: 'caresync-app-955fa',
    storageBucket: 'caresync-app-955fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5x9rBsrcZmPEvQWrj7zEKjd2D9W2XSY',
    appId: '1:623777701983:ios:your-ios-app-id',
    messagingSenderId: '623777701983',
    projectId: 'caresync-app-955fa',
    storageBucket: 'caresync-app-955fa.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5x9rBsrcZmPEvQWrj7zEKjd2D9W2XSY',
    appId: '1:623777701983:ios:your-ios-app-id',
    messagingSenderId: '623777701983',
    projectId: 'caresync-app-955fa',
    storageBucket: 'caresync-app-955fa.firebasestorage.app',
    iosBundleId: 'com.example.caresync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs5x9rBsrcZmPEvQWrj7zEKjd2D9W2XSY',
    appId: '1:623777701983:web:your-web-app-id',
    messagingSenderId: '623777701983',
    projectId: 'caresync-app-955fa',
    authDomain: 'caresync-app-955fa.firebaseapp.com',
    storageBucket: 'caresync-app-955fa.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
